#!/bin/bash

echo "🔥 Firebase ID Token Testing Guide"
echo "=================================="
echo ""
echo "Since your app isn't ready yet, here are 3 ways to get a Firebase ID token for testing:"
echo ""
echo "📋 METHOD 1: Use the HTML Test Page (EASIEST)"
echo "============================================="
echo "1. Open the file: test-firebase-auth.html in your browser"
echo "2. Get your Firebase config from Firebase Console:"
echo "   - Go to: https://console.firebase.google.com"
echo "   - Select your project: 'yatrasuraksha'"
echo "   - Go to Project Settings > General"
echo "   - Scroll down to 'Your apps' section"
echo "   - Copy the firebaseConfig object"
echo "3. Paste the config in the HTML page"
echo "4. Login with your test user credentials"
echo "5. Copy the ID token and use it for API testing"
echo ""
echo "📋 METHOD 2: Use Firebase CLI (RECOMMENDED)"
echo "==========================================="
echo "1. Install Firebase CLI:"
echo "   npm install -g firebase-tools"
echo ""
echo "2. Login to Firebase:"
echo "   firebase login"
echo ""
echo "3. Get access token:"
echo "   firebase auth:export users.json --project yatrasuraksha"
echo ""
echo "📋 METHOD 3: Create a Test User via Firebase Console"
echo "==================================================="
echo "1. Go to Firebase Console > Authentication > Users"
echo "2. Click 'Add User'"
echo "3. Create a test user with email/password"
echo "4. Use the HTML page to login and get the token"
echo ""
echo "🧪 TESTING YOUR API"
echo "=================="
echo "Once you have the ID token, test your API with:"
echo ""
echo "curl -X POST 'http://localhost:3000/api/users/verify' \\"
echo "  -H 'Authorization: Bearer YOUR_ID_TOKEN_HERE' \\"
echo "  -H 'Content-Type: application/json'"
echo ""
echo "✅ The ID token should look like: eyJhbGciOiJSUzI1NiIsImtpZCI6..."
echo "   (A long JWT string with 3 parts separated by dots)"
echo ""
echo "❌ The UID looks like: abc123def456ghi789"
echo "   (A short string - this WON'T work for API authentication)"
echo ""
